version: "3.5"
services:
    db:
        image: mariadb:latest
        platform: linux/amd64
        restart: always
        env_file:
            - '.env'
        ports:
            - 33060:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'portal'
        networks:
            - shared_network
        volumes:
            - database-data:/var/lib/mysql

    # The main PHP application
    portal:
        depends_on:
            - db
            - redis
            - mailcatcher
        networks:
            - shared_network
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - 8082:80
        volumes:
            - .:/var/www/html
        user: "www-data"
        environment:
            DB_HOST: db # Cambiamos a 'db' en lugar de 'localhost'

    redis:
        image: redis:5.0-alpine
        ports:
            - "6379:6379"
        networks:
            - shared_network

    mailcatcher:
        image: mailhog/mailhog:latest
        platform: linux/amd64
        ports:
            - "1025:1025"
            - "8025:8025" # La interfaz web estará en el puerto 8025
        networks:
            - shared_network

    selenium-hub:
        image: selenium/hub:3.12.0-americium
        container_name: selenium-hub
        ports:
            - "4444:4444"
        networks:
            - shared_network

    chrome:
        image: selenium/node-chrome:3.12.0-americium
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
        networks:
            - shared_network

volumes:
    database-data:

networks:
    shared_network:
        driver: bridge
