# Azure Container Registry details
image:
    repository: ifrcsmdb.azurecr.io/whatnow
    tag: "latest"
    pullPolicy: Always

replicaCount: 1

# Kubernetes service configuration
service:
    type: ClusterIP
    port: 80
    targetPort: 80
# Environment variables
env:
    APP_NAME: 'IFRC National Society Preparedness Messages'
    APP_ENV: production
    APP_DEBUG: false
    APP_LOG_LEVEL: info
    APP_URL: https://preparemessages.ifrc.org
    GOOGLE_MAPS_KEY:
    DB_CONNECTION: mysql
    DB_PORT: 3306
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    SESSION_DRIVER: file
    QUEUE_DRIVER: sync
    REDIS_HOST: redis
    REDIS_PASSWORD: null
    REDIS_PORT: 6379
    MAIL_DRIVER: smtp
    MAIL_HOST: smtp.azurecomm.net
    MAIL_PORT: 587
    MAIL_ENCRYPTION: tls
    PUSHER_APP_ID:
    PUSHER_APP_KEY:
    PUSHER_APP_SECRET:
    RCN_API_VERSION: v2
    FACEBOOK_APP_ID:
    FACEBOOK_APP_SECRET:
    GOOGLE_CLIENT_ID:
    GOOGLE_CLIENT_SECRET:
    GOOGLE_ANALYTICS_TRACKER_ID:
    SENTRY_DSN:
    BUCKET_URL: https://smdbstorageaccount.blob.core.windows.net/images
    IFRC_TRANSLATION_APP_ID: 12
    IFRC_TRANSLATION_API_URL: https://ifrcumicroservicesapim001.azure-api.net/translation/api



secrets:
    dbSecretName: backoffice-credentials
    variables:
        DB_HOST: BACKOFFICE_DB_HOST
        DB_DATABASE: BACKOFFICE_DB_DATABASE
        DB_USERNAME: BACKOFFICE_DB_USERNAME
        DB_PASSWORD: BACKOFFICE_DB_PASSWORD
        APP_KEY: BACKOFFICE_APP_KEY
        JWT_SECRET: BACKOFFICE_JWT_SECRET
        RCN_API_URL: BACKOFFICE_RCN_API_URL
        RCN_API_USER: BACKOFFICE_RCN_API_USER
        RCN_API_PASSWORD: BACKOFFICE_RCN_API_PASSWORD
        MAIL_ENDPOINT: MAIL_ENDPOINT
        MAIL_FROM: MAIL_FROM
        IFRC_TRANSLATION_API_KEY: IFRC_TRANSLATION_API_KEY
        MAIL_API_KEY: MAIL_API_KEY


ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
        - host: "preparemessages.ifrc.org"
          paths:
              - path: /
                pathType: Prefix
        -   host: "whatnow.jazusoft.com"
            paths:
                -   path: /
                    pathType: Prefix
    tls:
        - hosts:
              - "preparemessages.ifrc.org"
          secretName: "ifrc.certificates.secret"
        - hosts:
              - "whatnow.jazusoft.com"
          secretName: "jazusoft.certificates.secret"
